version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/maastokartoitus-app

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: node-v1-{{ checksum "maastokartoitus-app/package.json" }}-{{ arch }}

      - run: yarn install

      - save_cache:
          key: node-v1-{{ checksum "maastokartoitus-app/package.json" }}-{{ arch }}
          paths:
            - node_modules

      - run: yarn test
