export default {
  headerBackground:     '#3498DB',
  white:                '#FFFFFF',
  red:                  '#FF0000',
  neutralColor:         '#1D76B2',
  positiveColor:        '#5CB85C',
  negativeColor:        '#D9534F',
  neutralButton:        '#1D76B2',
  positiveButton:       '#5CB85C',
  negativeButton:       '#D9534F',
  inputBorder:          '#DEDEDE',
  blueBackground:       '#D9EDF7',
  obsColor:             '#0000CD',
  trackColor:           '#FFD700',
  fecesColor:           '#7CFC00',
  nestColor:            '#800080',
}